### ISSUE TITLE
Let's decide the way we are configuring cli params

### ISSUE THREAD

**Issue by ddimitrioglo** [TerraHubCorp/terrahub#121]
As we discussed `-var`, `-backend-config` and `-var-file` should follow [terrahub documentation ](https://www.terraform.io/docs/configuration/variables.html)

But I see changes [here](https://github.com/MitocGroup/terrahub/blob/dfa51800309caad8c082a063078184a94cc18a6b/src/helpers/terraform.js#L96) and additional `@todo`.

Let's decide the way we are configuring cli params.

**Comment by eistrati** [comment]
not relevant anymore
