### ISSUE TITLE
When running `thub destroy -i resource` it shouldn't look for parents.

### ISSUE THREAD

**Issue by gcaraman** [TerraHubCorp/terrahub#182]
```
grigore@grigore-GL502VT:~/templates$ thub destroy -i ci-job-create-method-post-integration-response-200,ci-job-create-method-post-integration,ci-job-create-method-post,ci-job-create-method-post-response-200 --env dev
❌ Can not find parent './.terrahub/ci-job-create'
```
![screenshot from 2018-07-25 14-21-38](https://user-images.githubusercontent.com/33287021/43198107-231f1cd4-9016-11e8-80ab-5b955efa16b0.png)

**Comment by eistrati** [comment]
1. If `thub destroy` s3 resource without cf, throw an error saying "Cannot destroy resource `cf` because it's a dependency for resource `s3`"
2. If `thub destroy` both s3 and cf, follow the order of removing cf first and s3 second

**Comment by gcaraman** [comment]
@eistrati I don't know if I understood you correctly, but I think the new behavior should be like this:
1. If cf depends on s3 (s3 is the parent), you should be able to destroy cf without any problems.
2. If cf depends on s3 and you try to destroy s3, an error should be thrown.
3. If cf depends on s3 and you try to destroy them both, first should be destroyed cf and then s3.

**Comment by eistrati** [comment]
That's correct!

**Comment by eistrati** [comment]
Checked.
