### ISSUE TITLE
Set item variables

### ISSUE THREAD

**Issue by vsitnic** [TerraHubCorp/terrahub#189]
Please develop a feature to set/save variables inside the item folder. It must work like `--var` option, but save variable in 'default.tfvars' file . 
Please prepare it for global configuration and for item configuration

**Comment by ddimitrioglo** [comment]
Hi @vsitnic, we are very close to implement this feature, but we still need more detailed explanation of what you expect.
Thanks.

**Comment by eistrati** [comment]
Implemented here: https://github.com/TerraHubCorp/terrahub/releases/tag/v0.0.28
Details: Use `terrahub configure -c 'terraform.var.key="value"'` or `terrahub configure -c 'terraform.var.key="value"' -i my_thub_component` to overwrite any variable from `default.tfvars`. Our approach is to NOT make any changes to TF files, but overwrite values at runtime by passing the as options to `terraform` cli.
