### ISSUE TITLE
Improve `terrahub run` execution time by implementing Status = SKIP for `terraform plan`

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#227]
In previous implementation via recink, we has such a feature that "skipped" execution of `terraform apply` because `terraform plan` returned "No infrastructure changes..."

Let's discuss and figure out if we would like to implement this feature.

**Comment by avozicov** [comment]
Requires to apply change request from @ddimitrioglo

**Comment by KanoniPan** [comment]
Test passed for remote state, `terrahub` is using the plan generated by `plan` command for `apply` command

<img width="1122" alt="2018-09-21 17 41 51" src="https://user-images.githubusercontent.com/35734669/45888147-0b909880-bdc6-11e8-8069-ec1d98baa7e3.png">

**Comment by Leichtwind** [comment]
**Expected Behavior**
Scenario: Skip redundant plan in `terrahub run --apply`
Given: I have `terrahub cli` and a `terrahub` component
When: I run `terrahub run --apply` or `terrahub run --destroy`
Then: I see only one `terraform plan` execution in console output

**Comment by ddimitrioglo** [comment]
@Leichtwind only see one plan or actually do it once?

**Comment by eistrati** [comment]
Checked.
