### ISSUE TITLE
Terrahub doesn't exit automatically

### ISSUE THREAD

**Issue by KanoniPan** [TerraHubCorp/terrahub#280]
## Describe the Bug
Terrahub doesn't exit automatically when an error occurred, but there are still components to run
## Steps to Reproduce
1. `terrahub project -n [projectName] -d [projectName]`
2. `terrahub component -n [invalidNameI] -t s3` (name should contain upper case)
3. `terrahub component -n [invalidNameII] -t s3 -o ../[invalidNameI]`
4. `thub run -a`

## Expected Behavior
Finish TerraHub process with error
## Screenshots
![image](https://user-images.githubusercontent.com/35734669/44586902-eeae7880-a7b9-11e8-8f35-0869bd59c3ed.png)

## Additional Context
- TerraHub Version: 0.0.21
- OS: macOs High Sierra 10.13.6

**Comment by KanoniPan** [comment]
Test Failed:
Next steps were performed:
- `thub project -n [Name] -d [FolderName] && cd ~/[FolderName]`
✅ Project successfully initialized
- `thub component -n [invalidNameI] -t s3`
✅ Done
- `thub component -n [invalidNameII] -t s3 -o ../[invalidNameI]`
✅ Done
- `thub run -a`
<img width="702" alt="2018-09-10 17 40 31" src="https://user-images.githubusercontent.com/35734669/45304720-5c300800-b521-11e8-97c8-c975c400c214.png">

## Expected Behavior

Finish TerraHub process with error

**Comment by KanoniPan** [comment]
Test Passed: 
Next steps were performed:
- `thub project -n [Name] -d [FolderName] && cd ~/[FolderName]`
✅ Project successfully initialized
- `thub component -n [invalidNameI] -t s3`
✅ Done
- `thub component -n [invalidNameII] -t s3 -o ../[invalidNameI]`
✅ Done
- `thub run -a`
<img width="1097" alt="2018-09-12 16 36 19" src="https://user-images.githubusercontent.com/35734669/45428648-5580cc80-b6aa-11e8-8ea0-8e7489a15d11.png">
Terrahub finish process automatically when error occurs

**Comment by eistrati** [comment]
Checked.
