### ISSUE TITLE
Improve hooks to support any executable, NOT ONLY javascript files

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#284]
## Describe the Feature

Improve hooks to support any executable, NOT ONLY javascript files

## Expected Behavior

Currently, hooks for terrahub commands like `init`, `workspace`, `plan`, `apply`, `destroy` and `output` support only javascript files. Let's extend the support for other executables like shell scripts, python scripts, go scripts, etc.

**Comment by ddimitrioglo** [comment]
I'll describe how to do this in documentation

**Comment by eistrati** [comment]
Checked.
