### ISSUE TITLE
Add `--git-diff` option to `terrahub run` to optimize / reduce the list of executed components

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#294]
## Describe the Feature

Add `--git-diff` option to `terrahub run` to optimize / reduce the list of executed components

## Expected Behavior

If option `--git-diff X..Y` (or `-g X..Y`) is passed to `terrahub run`, I expect the following to happen:
1. `git diff --name-only X Y` provides a list of files changed between commit X and commit Y
2. above list is compared to `ci.mapping` definitions across all `.terrahub.yml` config files and matched terrahub components are compiled into a list
3. if list is empty, execute `terrahub run`
4. if list is NOT empty, execute `terrahub run --include [above_list_as_csv]`
NOTE: in theory, a pull request can be viewed as a `git diff` between commit X and commit Y

**Comment by avozicov** [comment]
Pre-requisites:
`terrahub project -n [project_name]`
`terrahub component -n [component_a] -t [template_a]`
`terrahub component -n [component_b] -t [template_b]`
`ci mapping` is defined for project + components_a+b

Case 1:
- git is not initialized | git is not installed 
- run `terrahub run -g origin/master`

Expected:
- Error message is displaying and TerraHub run is aborted = **Passed**

Case 2:
- `mkdir src` in your local git repo 
-  `cd src && touch _config.json`
- configure project `.terrahub.yml` to listen to `../src/_config.json`
-  `code changes` step
- `git add .`
- `git commit -m #1`
-  `code changes` step
- `git add .`
- `git commit -m #2`
- `terrahub run -g [commit_id#1] [commit_id#2] 

Expected:
- TerraHub command executed for both components and for all project = **Passed**

Case 3:
- configure component A `.terrahub.yml` to listen to `./README.md` of 
-  `code changes` in README.md file step
- `git add .`
- `terrahub run -g [local_branch] [remote_branch]`

Expected:
- TerraHub command executed for component A only and skips execution for component B = **Passed**

**Comment by eistrati** [comment]
Checked.
