### ISSUE TITLE
Use `terrahub plan` implementation for `apply` and `destroy` commands

### ISSUE THREAD

**Issue by Leichtwind** [TerraHubCorp/terrahub#314]
## Describe the Feature

Now when #227 and https://github.com/MitocGroup/terrahub-api/issues/433 is implemented I have the next proposal:
We can make `terrahub apply` and `destroy` commands use `terrahub plan` implementation. Then this plan can be parsed by `terrahub api` and the result displayed in the UI as `to be added`, `to be changed` and `to be destroyed`
Also I guess it would be a nice idea to add `destroy` option to `terrahub plan` command that generates plan for `terraform destroy` action

Note: with implementation of this feature `apply` and `destroy` actions will generate `plan` record in realtime which will be displayed in the UI

## Expected Behavior

1. `terrahub plan --destroy` option generates plan for `terraform destroy` action
2. `terrahub apply` option uses `terrahub plan` implementation. Generated plan is parsed by `terrahub api`
3. `terrahub destroy` option uses `terrahub plan` implementation. Generated plan is parsed by `terrahub api`

**Comment by Leichtwind** [comment]
@eistrati @ddimitrioglo what you think about this feature?

**Comment by eistrati** [comment]
Let's skip `terrahub plan` step in `terrahub run` execution IF there are NO `hook.plan.before` and `hook.plan.after`

**Comment by eistrati** [comment]
Let's display plan before asking to continue if `terrahub run` / `terrahub apply` / `terrahub destroy` is executed only on 1 component

**Comment by eistrati** [comment]
Checked.
