### ISSUE TITLE
Add possibility to use regex with `include` and `exclude` options

### ISSUE THREAD

**Issue by Leichtwind** [TerraHubCorp/terrahub#315]
## Describe the Feature

Sometimes `terrahub` customers would like to execute some actions only with a specific group of `terrahub` components. I guess regex is just the solution for this case.

## Expected Behavior

- Option `--include-regex` to include components matching regex
- Option `--exclude-regex` to exclude components matching regex

**Comment by Leichtwind** [comment]
@eistrati @ddimitrioglo What do you think about this proposal?

**Comment by avozicov** [comment]
In this use case we expect that regular expression can be used for terrahub commands which support include and exclude options.

To test this I have created two components => `aws_iam_role` + `aws_iam_policy` which contains `iam` word and initialized terrahub provider by running `terrahub init -I iam` with the expected result that init will be applied for both components = **Passed**

<img width="687" alt="screen shot 2018-09-28 at 13 47 24" src="https://user-images.githubusercontent.com/12330493/46204205-1185fc80-c325-11e8-8531-0491e09b44c4.png">

Same with exclude option 

<img width="519" alt="screen shot 2018-09-28 at 13 50 39" src="https://user-images.githubusercontent.com/12330493/46204329-85280980-c325-11e8-94ed-5f4574b9aa9a.png">

**Comment by eistrati** [comment]
Checked.
