### ISSUE TITLE
Implement `terrahub refresh` command

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#316]
TBU ...

**Comment by avozicov** [comment]
To test this we can remove the `tfstate` file from component directory and when re-run `terrahub refresh --var=account_id:$CLOUD_ACCOUNT` it is expected to create a new `tfstate` file  = 
**Passed**

<img width="1041" alt="screen_shot_2018-09-28_at_13_26_01" src="https://user-images.githubusercontent.com/12330493/46203344-2f9e2d80-c322-11e8-8f9b-d932dab6985a.png">

**Comment by eistrati** [comment]
Checked.
