### ISSUE TITLE
Add config option to limit `terrahub` execution by physical threads

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#319]
When `terrahub` is running inside child process it is expected to be limited by one thread

**Comment by Leichtwind** [comment]
Expected Behaviour:
Given: I have global `terrahub` config file with `useLogicalThreads` field set to `false`
Expected: When I run one of the `terraform execution` commands I see `terrahub` creates as many sub processes as many physical threads my computer has

**Comment by avozicov** [comment]
**Passed**

I was able to configure terrahub to use physical threads instead of logical under global config.

FYI:
- I have added console.log of used thread just for testing, it is not a part of codebase

<img width="966" alt="screen shot 2018-11-09 at 19 33 46" src="https://user-images.githubusercontent.com/12330493/48278576-9b61d300-e456-11e8-8b76-a5f74042063c.png">

**Comment by eistrati** [comment]
Checked.
