### ISSUE TITLE
Implement `terrahub plan` to be used for  `terrahub apply` command

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#320]
## Expected Behavior
It is expected for `terrahub apply` to use **terrahub** plan instead of **terraform** plan

**Comment by avozicov** [comment]
In this case when running `terrahub apply --var=account_id:$CLOUD_ACCOUNT -y` no new plan is generated for terrahub apply, but plan_path used from plan action is used for apply action.

We can see from the screenshoot that second plan was not generated, instead plan path was provided and used for apply =  **Passed**   

<img width="755" alt="screen_shot_2018-09-28_at_13_35_45" src="https://user-images.githubusercontent.com/12330493/46203847-bd2e4d00-c323-11e8-9508-4e0f60978ae8.png">

**Comment by eistrati** [comment]
Checked.
