### ISSUE TITLE
Improve workflow execution for terrahub run / plan / apply / destroy

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#339]
## Describe the Feature

Improve workflow execution for terrahub run / plan / apply / destroy

### Global Use Case
If terraform plan returns "No infrastructure changes", SKIP executing `apply` or `destroy`

### Use Case 1
`terrahub run`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan` with `hook.plan.before` and `hook.plan.after`, if defined

### Use Case 2
`terrahub run --apply`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan` is executed with Status == "Skip"
4. `terrahub apply` with `hook.apply.before` and `hook.apply.after`, if defined

### Use Case 3
`terrahub run --destroy`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan --destroy` is executed with Status == "Skip"
4. `terrahub destroy` with `hook.destroy.before` and `hook.destroy.after`, if defined

### Use Case 4
`terrahub run --apply --destroy`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan` is executed with Status == "Skip"
4. `terrahub apply` with `hook.apply.before` and `hook.apply.after`, if defined
5. `terrahub plan --destroy` is executed with Status == "Skip"
6. `terrahub destroy` with `hook.destroy.before` and `hook.destroy.after`, if defined

### Use Case 5
`terrahub plan`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan` is executed with Status == "Success" and with `hook.apply.before` and `hook.apply.after`, if defined

### Use Case 6
`terrahub apply`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan` is executed with Status == "Success"
4. `terrahub apply` with `hook.apply.before` and `hook.apply.after`, if defined

### Use Case 7
`terrahub destroy`
1. `terrahub init` with `hook.init.before` and `hook.init.after`, if defined
2. `terrahub workspace` with `hook.workspace.before` and `hook.workspace.after`, if defined
3. `terrahub plan --destroy` is executed with Status == "Success"
4. `terrahub destroy` with `hook.destroy.before` and `hook.destroy.after`, if defined

**Comment by KanoniPan** [comment]
I propose the following output message for action aborted. I guess it makes more sense because only one of the steps is skipped, but not the whole action.

<img width="653" alt="2018-11-19 13 29 42" src="https://user-images.githubusercontent.com/35734669/48704665-dd7dd800-ebff-11e8-9b86-fc9d081e8878.png">

**Comment by eistrati** [comment]
Let's replace `aborted` with `skipped`

**Comment by eistrati** [comment]
Not relevant anymore
