### ISSUE TITLE
After apply hook is not executed if a resource was deployed successfully 

### ISSUE THREAD

**Issue by vcalmic** [TerraHubCorp/terrahub#341]
## Describe the Bug
If a resource was successfully executed, `after apply hook` is not executed.

## Steps to Reproduce

1. Add in `terrahub.yml` the following content: 
```
hook:
  apply:
    after: touch hook_apply
```
2. Run `terrahub run -a -y -i [resource]`

## Expected Behavior

If the apply was successfull, this hook needs to be executed. 

## Additional Context

- TerraHub Version: 0.0.24

**Comment by ddimitrioglo** [comment]
@vcalmic hooks in TerraHub are `.js` or `.sh` files NOT commands, and those files can not consume any parameters.

`cat /my/project/path` **Wrong** 
`/my/project/path/hook.sh param1 param2` **Wrong** 
`/my/project/path/hook.sh` **OK**

**Comment by vcalmic** [comment]
@Leichtwind could you add functionality in order to use `/my/project/path/hook.sh param1 param2` as @ddimitrioglo described?

**Comment by KanoniPan** [comment]
1. `*.js` with no args is executed as part of component process. It receives component config and command output as the first and the second args respectively
2. `*.sh` with args is executed as sub process
3. any commands with args are executed as sub process

**Comment by avozicov** [comment]
**Passed**

I have configured component .yml and added after apply hooks:
```

**Comment by eistrati** [comment]
Checked.
