### ISSUE TITLE
If a resource is depending on another resource, it should start after the parent resource was applied

### ISSUE THREAD

**Issue by vcalmic** [TerraHubCorp/terrahub#342]
## Describe the Bug

If a resource is depending on another resource, it should start after the parent resource was applied

## Steps to Reproduce

1. Create two resources. One depends on the other.
2. Run the command: `terrahub run -a -y`

## Expected Behavior

The parent resource should run first and child resource should start after the parent was applied.

## Additional Context

- TerraHub Version: 0.0.24

**Comment by Leichtwind** [comment]
@vcalmic I couldn't reproduce this bug. I have used the following project for testing.
![image.png](https://images.zenhubusercontent.com/5b212bc7083e2070577c11e7/8fb4f5fd-5388-45f4-b509-d1f815918951)
All components are AWS IAM Roles. `init`, `workspace` and `plan` action were executed in parallel. `apply` action was executed in parallel for `anotheronebitesthedust` and `bohemianrapsody`. Then it was executed for `dontstopmenow`.

Can you please provide some additional data that could help to reproduce the bug?
Please, execute, `terrahub graph` in your project and send me the result.

**Comment by vcalmic** [comment]
@Leichtwind `plan` should not execute in parallel. We need to execute `plan` after the parent was applied

**Comment by Leichtwind** [comment]
@vcalmic Okay. This requirement was different before. I will fix it now

**Comment by Leichtwind** [comment]
@vcalmic I have made a mistake. `plan` and `apply` are executed together. So now `terrahub` does it the following way:

**First Step**
- `plan` and `apply` for both `anotheronebitesthedust` and `bohemianrapsody`

**Second Step**
- `plan` and `apply` are executed for `dontstopmenow` after the `bohemianrapsody` is applied

**Comment by vcalmic** [comment]
@vcalmic Great!!!

**Comment by eistrati** [comment]
Checked.
