### ISSUE TITLE
Error when running `terrahub plan` for `terrahub-api` project

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#343]
## Describe the Bug
I have faced an error when trying to run `terrahub plan` command for our `terrahub-api` project
```
(node:2710) UnhandledPromiseRejectionWarning: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at promiseSeries.then.catch.error (/Users/alexandrvozicov/Projects/terrahub/src/helpers/worker.js:44:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async functionwithout a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce
1. cd `terrahub-api`
2. Run the command `THUB_API=api-[env] THUB_TOKEN=[your_terrahub_token] terrahub plan -e [env] -var=account_id:[aws_account_id]`

## Screenshots

<img width="837" alt="logg issue" src="https://user-images.githubusercontent.com/12330493/46352011-701ee380-c661-11e8-82c2-457496300f7e.png">

## Additional Context

- TerraHub Version: 0.0.24 
- OS: macOS Mojave 10.14

**Comment by eistrati** [comment]
```$ THUB_API=api THUB_TOKEN=*** terrahub plan -i s3_public -e master -var="account_id:***"
v0.0.40
```

**Comment by avozicov** [comment]
Deployed in Production 05.12.2018 using Jenkins and job succeed.
Please move back to Review and add info what addition steps are required for testing this.

**Comment by eistrati** [comment]
Checked.
