### ISSUE TITLE
Add functionality to `terrahub configure` command to remove `terrahub` configuration parameter

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#374]
## Describe the Feature

Add option to `terrahub configure` command `--delete` with alias `-D`.
`terrahub configure --delete key` should delete corresponding `key` configuration parameter

## Expected Behavior

Use Case 1: `terrahub configure -c terraform.var.region -D` will remove `terraform.var.region` from project / root config
Use Case 2: `terrahub configure -c terraform.var.s3_key -i s3_bucket -D` will remove `terraform.var.s3_key` from `s3_bucket` component / local config
Use Case 3: `terrahub configure -c terraform.var.format -D -G` will remove `terraform.var.format` from global config

**Comment by KanoniPan** [comment]
after discussion with Dmitri and Maxim it was decided to refactor the current solution with HashTable, i will work on it when i have time.

**Comment by avozicov** [comment]
**Passed**

<img width="894" alt="screen shot 2018-11-09 at 19 47 23" src="https://user-images.githubusercontent.com/12330493/48279140-53dc4680-e458-11e8-97af-4ae4ebcbae23.png">
<img width="757" alt="screen shot 2018-11-09 at 19 47 35" src="https://user-images.githubusercontent.com/12330493/48279141-53dc4680-e458-11e8-918b-6124959497a5.png">

**Comment by eistrati** [comment]
@KanoniPan we agreed NOT to leave `{}` and completely remove config if there are no values anymore

```
$ cat .terrahub.yml 
## project config
project:
  name: 'QA'
  code: '7a4d53eb'
  provider: 'aws'
  include:
    - '.'
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
hook:
  init:
    before: echo "TEST"

$ thub configure -c hook.init.before -D
✅ Done

$ cat .terrahub.yml 
project:
  name: QA
  code: 7a4d53eb
  provider: aws
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
hook:
  init: {}
```

EXPECTED:
```
$ cat .terrahub.yml 
project:
  name: QA
  code: 7a4d53eb
  provider: aws
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
```

**Comment by avozicov** [comment]
Use Case 1 = Passed

<img width="1440" alt="screen shot 2019-01-22 at 7 13 25 pm" src="https://user-images.githubusercontent.com/12330493/51552791-07f74600-1e7a-11e9-9c0f-c358ef5ab2e7.png">
<img width="936" alt="screen shot 2019-01-22 at 7 14 11 pm" src="https://user-images.githubusercontent.com/12330493/51552793-07f74600-1e7a-11e9-9909-54ec3f241423.png">


Use Case 2 = Passed

<img width="1120" alt="screen shot 2019-01-22 at 7 17 03 pm" src="https://user-images.githubusercontent.com/12330493/51552931-67555600-1e7a-11e9-94ea-3e7060442dfa.png">
<img width="1062" alt="screen shot 2019-01-22 at 7 17 28 pm" src="https://user-images.githubusercontent.com/12330493/51552932-67edec80-1e7a-11e9-9c94-7f1c415ab257.png">

Use Case 3 = Passed

<img width="689" alt="screen shot 2019-01-22 at 7 19 56 pm" src="https://user-images.githubusercontent.com/12330493/51553179-e054ad80-1e7a-11e9-98e7-628b75ff972f.png">
<img width="638" alt="screen shot 2019-01-22 at 7 20 02 pm" src="https://user-images.githubusercontent.com/12330493/51553180-e054ad80-1e7a-11e9-891f-6fd8ed7157dd.png">

**Comment by eistrati** [comment]
Checked.
