### ISSUE TITLE
Do not allow to create two `projects` inside on `dir` with different config file format 

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#376]
To reproduce:

1. `mkrid QA`
2. `cd QA`
3. define file form in global config as `.yml`
4. `terrahub project -n [name]`
5. change file form in global config as `.json`
6. `terrahub project -n [name]`

Bug:
- two projects was created inside on dir with the different config file format (`.yml` + `.json`)

Expected:
- To not allow to create two `projects` inside on `dir` with different config file format by checking if project is already exist in directory display informative message

**Comment by Leichtwind** [comment]
12.10.2018 on the HO call with Eugene and Alexandr it was decided to improve `terrahub` cli the following way:
- `terrahub project` command creates new project with the config files format specified in the global `terrahub` config
- within the project `terrahub` will determinate the config format by project config file extension

This feature should fix this bug, improve user experience and predict new bugs related to config format

**Comment by avozicov** [comment]
Test **Passed**

- Created project with `.yaml` format
- Changed to `.json` format the global config in root
- Tried to run `terrahub project` in the same directory but with the different format this time
<img width="1036" alt="screen shot 2018-11-19 at 19 01 18" src="https://user-images.githubusercontent.com/12330493/48722777-8858bb00-ec2d-11e8-9d99-dc951eb558a4.png">

**Comment by eistrati** [comment]
Checked.
