### ISSUE TITLE
terrahub ‘configure’ crashes if value is not an instance of Object or Array

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#381]
## Steps to Reproduce

1. Run the command `terrahub configure -c 'hook.apply.after="./script/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH"'`

## Expected Behavior

When running this command it should change string to object

## Screenshots

![Screen Shot 2018-10-12 at 20.00.53.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/2f529e3b-52c0-46ad-847a-8cd796311ade)

**Comment by avozicov** [comment]
**Passed**
I was able to valid add additional configuration to .yaml by providing required data right from cli in project dir 

<img width="1338" alt="screen shot 2018-11-09 at 18 15 48" src="https://user-images.githubusercontent.com/12330493/48274225-82075980-e44b-11e8-8102-76513e9484fc.png">

**Comment by eistrati** [comment]
Checked.
