### ISSUE TITLE
thub component is creating non valid .terrahub.json

### ISSUE THREAD

**Issue by KanoniPan** [TerraHubCorp/terrahub#387]
## Describe the Bug
Running `terrahub component` with global json format generates non valid .terrahub.json file
## Steps to Reproduce

Run the command `thub component -t [template] -n [name]`

## Expected Behavior
To create valid .json file
## Screenshots

<img width="1439" alt="2018-10-19 17 10 25" src="https://user-images.githubusercontent.com/35734669/47223537-2d2f7080-d3c2-11e8-84f3-dc145c09daf9.png">

**Comment by avozicov** [comment]
**Passed**

Valid .terrahub.json file was created 

<img width="1252" alt="screen shot 2018-11-09 at 18 30 29" src="https://user-images.githubusercontent.com/12330493/48275195-99474680-e44d-11e8-84ab-f2326967a396.png">

**Comment by eistrati** [comment]
Checked.
