### ISSUE TITLE
Fix `terrahub` resolves path by root path instead of component's for hooks

### ISSUE THREAD

**Issue by vcalmic** [TerraHubCorp/terrahub#395]
## Describe the Bug

Given: I have `terrahub` project  with a component named `foo`. `foo` config contains `hook.apply.before: bar.sh`. `bar.sh` is located in `./foo`.
When: I execute `terrahub apply`
Then: I see an error that `terrahub` tries to execute `./bar.sh`
Expected: I see `terrahub` executes `./foo/bar.sh`

**Comment by avozicov** [comment]
**Passed**
- I have configured run.sh script to echo TEST and place it inside created component
- Added hook config in .terrahub.yml of component
- Executed terrahub command with no errors for sh script path and the following output:

<img width="1282" alt="screen shot 2018-11-09 at 18 35 50" src="https://user-images.githubusercontent.com/12330493/48275631-a44ea680-e44e-11e8-95bc-6b0ebe3f92d1.png">

**Comment by eistrati** [comment]
Checked.
