### ISSUE TITLE
Improve confirmation question for terrahub `action` that expects yes/no answer

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#397]
## Describe the Feature

Improve confirmation question for terrahub `action` that expects yes/no answer

## Expected Behavior

Expected question should be:
- Line 1: `Are you sure you want to execute '${action_name}' action for below components?`
- Line 2: If there are less than 5 components, show them in a tree (similar to `terrahub graph`);
Otherwise it should look similar to this: `Project: X | Component(s): Y1, Y2, ....`

**Comment by avozicov** [comment]
**Passed**

<img width="503" alt="screen shot 2018-11-09 at 19 48 59" src="https://user-images.githubusercontent.com/12330493/48279280-c8af8080-e458-11e8-806a-d4ca055b45b8.png">
<img width="1051" alt="screen shot 2018-11-09 at 19 49 36" src="https://user-images.githubusercontent.com/12330493/48279281-c8af8080-e458-11e8-96cc-e67b9cc1405a.png">

**Comment by eistrati** [comment]
Checked.
