### ISSUE TITLE
Terrahub throws an error instead of showing custom message

### ISSUE THREAD

**Issue by KanoniPan** [TerraHubCorp/terrahub#399]
## Describe the Bug

When running `terrahub apply` with dependsOn which doesn't exists, it froms error instead of custom message
## Steps to Reproduce

1. create component using `terrahub component -n [name] -t [template]`
2. add dependsOn in `.terrahub.yml` with component which doesn't exists.
3. `terrahub apply` or `terrahub run`
4. see the error

```root@DESKTOP-ECSQPB1:/mnt/c/Terrahub/demo-terraform-google# THUB_API=api-test terrahub run -y -a -d -i=project_service_account
❌ TypeError: Cannot read property 'name' of undefined
    at RunCommand.checkDependencies (/mnt/c/Terrahub/terrahub/src/terraform-command.js:431:80)
    at Promise.resolve.then (/mnt/c/Terrahub/terrahub/src/commands/run.js:48:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

## Expected Behavior

Custom user-friendly error message is shown
## Additional Context

- TerraHub Version: [e.g. 22]

**Comment by avozicov** [comment]
**Passed**

<img width="808" alt="screen shot 2018-11-09 at 18 11 30" src="https://user-images.githubusercontent.com/12330493/48273961-ec6bca00-e44a-11e8-88be-d4e9bfb5ff44.png">

**Comment by eistrati** [comment]
```
$ thub --version
v0.0.40

$ ls -al
total 8
drwxr-xr-x   4 eugene  staff   136 Nov 10 12:57 .
drwxr-xr-x  54 eugene  staff  1836 Nov 10 12:57 ..
-rw-r--r--   1 eugene  staff   586 Nov 10 12:57 .terrahub.yml
drwxr-xr-x  11 eugene  staff   374 Nov 10 12:59 QAC

$ cat QAC/.terrahub.yml 
## local config
component:
  name: 'QAC'
  dependsOn:
    - './test'
  mapping:
    - '.'

$ ls -al QAC/
total 64
drwxr-xr-x  11 eugene  staff   374 Nov 10 12:59 .
drwxr-xr-x   4 eugene  staff   136 Nov 10 12:57 ..
drwxr-xr-x   3 eugene  staff   102 Nov 10 12:59 .terraform
-rw-r--r--   1 eugene  staff    90 Nov 10 12:58 .terrahub.yml
-rw-r--r--   1 eugene  staff  1501 Nov 10 12:57 README.md
-rw-r--r--   1 eugene  staff   375 Nov 10 12:57 data.tf
-rw-r--r--   1 eugene  staff   717 Nov 10 12:57 default.tfvars
-rw-r--r--   1 eugene  staff   335 Nov 10 12:57 main.tf
-rw-r--r--   1 eugene  staff   377 Nov 10 12:57 output.tf
-rw-r--r--   1 eugene  staff   115 Nov 10 12:57 provider.tf
-rw-r--r--   1 eugene  staff  1714 Nov 10 12:57 variables.tf

$ thub run
💡 [QAC] terraform init -no-color -input=false .
[QAC] 
[QAC] Initializing provider plugins...
[QAC] 
[QAC] Terraform has been successfully initialized!
```

**Comment by KanoniPan** [comment]
considering our terrahub dependency check is executed only for apply or destroy actions( or run with corresponding actions), there is an mistake in the description

**Comment by eistrati** [comment]
@KanoniPan I'm sorry for not being clear ... As you can see, I put a dependency that doesn't exist. Instead of getting an error, `terrahub run` works without errors, which is not OK. Please fix it.

**Comment by avozicov** [comment]
Test **Passed**

<img width="747" alt="screen shot 2018-11-19 at 19 08 20" src="https://user-images.githubusercontent.com/12330493/48723133-82afa500-ec2e-11e8-95cc-c51bd5f9201a.png">

**Comment by eistrati** [comment]
Checked.
