### ISSUE TITLE
`terrahub run` doesn’t update lambdas 

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#400]
Issue is started to reproduce in the latest code changes.
Please refer bellow for details:

https://github.com/TerraHubCorp/terrahub/blob/dev/src/templates/aws/lambda_function/scripts/compare.sh#L42

**Comment by ddimitrioglo** [comment]
@avozicov could you please provide debugging info by adding `DEBUG=debug`

**Comment by avozicov** [comment]
Fixed.
I have successfully deployed test environment for api and lambdas were updated.

Job log:
https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-api/1742/console 

AWS Lambda updates info

<img width="1133" alt="screen_shot_2018-11-21_at_20_12_05" src="https://user-images.githubusercontent.com/12330493/48860561-e91cfa80-edc9-11e8-874b-045d65f5343d.png">

**Comment by eistrati** [comment]
Checked.
