### ISSUE TITLE
Error when executing `terrahub project` command

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#417]
## Describe the Bug
I am facing the following error when trying to execute `terrahub project` 

## Steps to Reproduce

1. Run the command 'terrahub project -n -d'

## Expected Behavior
Project directory should be created

## Additional Context

- TerraHub Version: 0.0.34

## Screenshots

<img width="762" alt="screen shot 2018-11-07 at 19 20 54" src="https://user-images.githubusercontent.com/12330493/48148575-c4e9f580-e2c2-11e8-9abe-55853e744cb4.png">

**Comment by avozicov** [comment]
Fixed in latest `dev` branch

**Comment by avozicov** [comment]
Fixed and deployed as hotfix up to production

<img width="1286" alt="screen shot 2018-11-09 at 18 28 39" src="https://user-images.githubusercontent.com/12330493/48275077-55544180-e44d-11e8-95a6-6efd11f5ff8e.png">

**Comment by eistrati** [comment]
Checked.
