### ISSUE TITLE
Terrahub destroy with -i/-I option is not working

### ISSUE THREAD

**Issue by KanoniPan** [TerraHubCorp/terrahub#419]
## Describe the Bug

When running `terrahub destroy -I [name]` it causes next error:
TerraHub failed because of the following issues:
1. 'undefined' component that depends on  component is excluded from the execution list
2. '[name]' component that depends on  component is excluded from the execution list`
## Steps to Reproduce

- `terrahub project -n [projectName] -d [projectName] && cd [name]`
✅ Project successfully initialized
- `terrahub component -n [name1] -t aws_iam_role`
✅ Done
- `terrahub component -n [name2] -t aws_iam_role`
✅ Done
- `thub destroy -i [name1]`
❌ TerraHub failed because of the following issues:
1. 'undefined' component that depends on  component is excluded from the execution list
2. '[name1]' component that depends on  component is excluded from the execution list

## Expected Behavior

To perform destroy command for included components
## Screenshots

<img width="637" alt="2018-11-08 12 23 05" src="https://user-images.githubusercontent.com/35734669/48192652-104ae500-e351-11e8-9b53-dbce17d1f18d.png">

**Comment by avozicov** [comment]
**Fixed**

<img width="633" alt="screen shot 2018-11-09 at 19 42 01" src="https://user-images.githubusercontent.com/12330493/48278898-8f2a4580-e457-11e8-890a-de5f55bdda19.png">

**Comment by eistrati** [comment]
Checked.
