### ISSUE TITLE
Terrahub destroy crashes on invalid dependency

### ISSUE THREAD

**Issue by KanoniPan** [TerraHubCorp/terrahub#434]
## Describe the Bug

Given: I have a terrahub project with 2 components, one of the components depends on non-existing component
When: I run `terrahub destroy` or `terrahub run --destroy`
Then: I see terrahub crashes with error
<img width="781" alt="2018-11-13 10 57 33" src="https://user-images.githubusercontent.com/35734669/48402096-6e9e0c00-e733-11e8-845f-1f42ac5e0c82.png">
Expected: I see terrahub shows custom error

**Comment by eistrati** [comment]
Checked.
