### ISSUE TITLE
Aliases are not predictable

### ISSUE THREAD

**Issue by ddimitrioglo** [TerraHubCorp/terrahub#440]
Are we sure that our customers will know that `terrahub` is named as `thub`?

![image](https://user-images.githubusercontent.com/9005667/48561026-c6857000-e8f7-11e8-9aa7-c56b72c4803e.png)

**Comment by eistrati** [comment]
Technically we don't have `terrhub`. Instead we have `terrahub` as long command and `thub` as short command. I believe we could mention that we provide an alias.

@ddimitrioglo @Leichtwind @KanoniPan What do you guys think?

**Comment by ddimitrioglo** [comment]
😆 Sorry guys, it just a typo.
