### ISSUE TITLE
Error when trying to create project with `terrahub project` command

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#441]
## Describe the Bug
I am not able to create project using `terrahub project` command.
Bug is reproduced in 0.0.40 and ^ versions 

## Steps to Reproduce
1. mkdir Debug
2. cd Debug
3. terrahub project -p aws -n AWS_QA_PROJECT -d ./AWS_QA_PROJECT

BUG:
- Error message is displayed with the text `💡 Project already configured` and as a result project can not be created in spite the fact that Debug directory is empty 

## Expected Behavior

- AWS_QA_PROJECT should be created
- .terrahub.yml should be created inside Test directory 

## Screenshots

![Screen Shot 2018-11-15 at 17.13.30.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/0fd1ed52-dd4e-468b-9b78-b807e5b10098)

**Comment by Leichtwind** [comment]
@avozicov I can't reproduce the bug
![image](https://user-images.githubusercontent.com/35968905/48569334-10775180-e90a-11e8-9772-e20c0d901272.png)

**Comment by KanoniPan** [comment]
me either
<img width="672" alt="2018-11-15 19 12 53" src="https://user-images.githubusercontent.com/35734669/48569459-795ec980-e90a-11e8-9579-ed4d2124ed40.png">

**Comment by ddimitrioglo** [comment]
Are you guys working with the same version?

**Comment by avozicov** [comment]
I think that in this case we should add a message something like `Project is already configured in [path] directory`, otherwise if it was a confusing for @euliancom, @ddimitrioglo and @avozicov  - it will definitely be a confuse for end user ;)

**Comment by avozicov** [comment]
Test **Passed**

<img width="1092" alt="screen shot 2018-11-19 at 18 41 36" src="https://user-images.githubusercontent.com/12330493/48721553-d28c6d00-ec2a-11e8-86bd-5bb2e957f2df.png">

**Comment by eistrati** [comment]
Checked.
