### ISSUE TITLE
Add status skip for `workspace` action 

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#453]

**Comment by avozicov** [comment]
Workspace action were skipped because default workspace was already chosen

<img width="1332" alt="screen shot 2018-11-26 at 17 46 38" src="https://user-images.githubusercontent.com/12330493/49024982-569ea180-f1a3-11e8-8944-a096d04c2d25.png">

**Comment by eistrati** [comment]
Checked.
