### ISSUE TITLE
Add terrahub build as a step in terrahub run

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#459]
## Describe the Feature

Add terrahub build as a step in terrahub run

## Expected Behavior

Add terrahub build as a step in terrahub run

**Comment by avozicov** [comment]
Failed.
Build step was executed after plan action.

Pending release the following fix to retest https://github.com/TerraHubCorp/terrahub/pull/569

**Comment by eistrati** [comment]
Checked.
