### ISSUE TITLE
Add user friendly and informative message when trying to delete inexistent component

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#465]
## Steps to Reproduce

1. Create terrahub component A
2. Run the command `terrahub component -n A -D`
3. Run the command `terrahub component -n A -D` once again 

## Expected Behavior

It is expected to have an user friendly and informative message when trying to delete inexistent component

## Actual Behavior
Error is displayed 

<img width="771" alt="2018-11-26 16 19 09" src="https://user-images.githubusercontent.com/12330493/49019643-10434580-f197-11e8-9bd8-84644699ba6a.png">

**Comment by avozicov** [comment]
Actual implementation is wrong:

<img width="598" alt="screen shot 2019-01-22 at 5 59 34 pm" src="https://user-images.githubusercontent.com/12330493/51548442-fd847e80-1e70-11e9-9e8a-53457134e0b1.png">



I would suggest to improve it in the following way:
1. When running `terrahub component -n A -D` and there is no "A" component display the notification message and do not display list of inexistent components in output 

2. Case when multiple inexistent components provided in destroy command, display them as array in one message instead of displaying the notification message for each inexistent components

**Comment by avozicov** [comment]
Fixed:

```
Alexandrs-MacBook-Pro:test alexandrvozicov$ ll
total 8
drwxr-xr-x   4 alexandrvozicov  staff  128 Apr 17 13:45 .
drwxr-xr-x  12 alexandrvozicov  staff  384 Apr 17 13:35 ..
-rw-r--r--   1 alexandrvozicov  staff  591 Apr 17 13:44 .terrahub.yml
drwxr-xr-x   5 alexandrvozicov  staff  160 Apr 17 13:46 lambda
Alexandrs-MacBook-Pro:test alexandrvozicov$ terrahub component -n lambda,test,hello -D 
❌ Terrahub components with provided names 'test', 'hello' don't exist.
Alexandrs-MacBook-Pro:test alexandrvozicov$ 
```

**Comment by eistrati** [comment]
Checked.
