### ISSUE TITLE
Improve confirmation message when running terrahub output command

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#467]
I guess we can improve actual confirmation message when running `terrahub output` command otherwise it can be confusing for user when he answering with `Y` and expecting that `terrahub apply` action will be performed.

To reproduce this use case please follow these steps:
1. Configure new terrahub component 
2. Run `terrahub output` command
3. Answer `Y` to the confirmation message from TerraHub

Actual Result:
- `terrahub output` action is performed 

<img width="805" alt="screen shot 2018-11-26 at 18 00 32" src="https://user-images.githubusercontent.com/12330493/49029505-72a74080-f1ad-11e8-95ce-16ef493bd801.png">

Expected Result:
- Confirmation message should be improved

**Comment by eistrati** [comment]
not relevant anymore
