### ISSUE TITLE
Worker error when trying to deploy terrahub-api

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#471]
We have faced the following error when trying to deploy *terrahub-api* in Jenkins job

```
[lambda_github_webhook_trigger] download: s3://data-lake-terrahub-us-east-1/deploy/mitocgroup/terrahub-api/dev/lambda_github_webhook_trigger/nodejs8.10.txt to ./nodejs8.10.txt
❌ Worker error: {}
```

Please refer to Jenkins log for more details:
https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-api/1779/console

Please investigate and apply required fixes

**Comment by KanoniPan** [comment]
fixed in [https://github.com/MitocGroup/terrahub-api/pull/849](url)

**Comment by avozicov** [comment]
Deployed in Production 05.12.2018 using Jenkins and job succeed.
Please move back to Review and add info what addition steps are required for testing this.

**Comment by eistrati** [comment]
Checked.
