### ISSUE TITLE
Collect and submit to terrahub api user identity and error messages when valid token is setup

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#479]
## Describe the Feature

Collect and submit to terrahub api user identity and error message when valid token is setup

## Expected Behavior

Current implementation of cloudtrail collects and submits user identity and error messages. Let's extend this feature to terrahub cli when valid token is setup.

**Comment by KanoniPan** [comment]
1. Add to `payload` error message 
2. Add `user` who ran the action so we can show him on UI

**Comment by eistrati** [comment]
Not relevant anymore
