### ISSUE TITLE
Refactor terrahub token validation to allow executions of terrahub commands that don't depend on terrahub api

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#504]
## Describe the Feature

Refactor terrahub token validation to allow executions of terrahub commands that don't depend on terrahub api

## Expected Behavior

Right now, if my TerraHub token is not valid and I'd like to create a new project, `terrahub project` execution fails with error `Provided THUB_TOKEN is invalid`. Let's think this and refactor our process to allow some executions to continue going forward, specifically the ones that don't depend on interaction with TerraHub API.

**Comment by eistrati** [comment]
@avozicov please review this one. looks like it's already implemented.

**Comment by avozicov** [comment]
Test Passed.

I have edited my valid THUB_TOKEN to another invalid and executed terrahub compoment and as a result component was created

![Screen Shot 2019-03-29 at 4.43.31 PM.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/c8bc3eff-cd1e-4231-be84-97ae7f9b4b3a)

**Comment by eistrati** [comment]
Checked.
