### ISSUE TITLE
Terrahub run continues to execute when init failed

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#505]
## Describe the Bug

Terrahub run continues to execute when init failed

## Steps to Reproduce

1. Setup wrong AWS credentials and execute `terrahub run -y`
2. Watch `init` command fail and continue the workflow to `workspace` and even `plan`

## Expected Behavior

Execution should stop after failed step (see log below):
```
$ terrahub run -y
💡 [s3_bucket] terraform init -no-color -input=false .
[s3_bucket] 
[s3_bucket] Initializing the backend...
❌ [s3_bucket] Error loading state: AccessDenied: Access Denied

❌ [s3_bucket] 	status code: 403, request id: 8C8D384DB48C5EAF, host id: OH2++5X3DEmyw4VTrjPRq3Gbz6+seAsBDMwaE/1nZLcyWs49K9EIgop2aI9CriH0IWHDj97xKmE=

💡 [s3_bucket] terraform workspace list
❌ [s3_bucket] AccessDenied: Access Denied

❌ [s3_bucket] 	status code: 403, request id: A56518A73A375C8D, host id: uPXSdel910VocUYgaY6ZVHli5sQZODjamcNztm4PQ2jmX/+GBv4/eJSUq1vG7tSM8gLaLxeIox4=

💡 [s3_bucket] terraform plan -no-color -var-file='./www/.terrahub/s3_bucket/default.tfvars' -out=./www/.terrahub/s3_bucket/terraform.tfplan -input=false
❌ [s3_bucket] 

❌ [s3_bucket] Error: Error loading state: AccessDenied: Access Denied
	status code: 403, request id: DA7ECB0C83540A7D, host id: K7HdszQ3kFuDIpfKbQOND7ST4E3DpI/DmJyL5bJqpFMfOFPCOYyPc/zm6GgiphFmnESwYhoEpOg=
```

**Comment by avozicov** [comment]
Test **Passed**

I have created created backend.tf and tried to run `terrahub run -y` without specifying valid credential for AWS Provider. As a result init step failed with the error message 

<img width="1438" alt="screen shot 2019-01-10 at 5 31 33 pm" src="https://user-images.githubusercontent.com/12330493/50978883-00d94b00-14fe-11e9-9059-a39fbc30321b.png">

**Comment by eistrati** [comment]
Checked.
