### ISSUE TITLE
Move path pattern from `~/.terrahub/jit/` into `~/.terrahub/cache/jit/`

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#548]

**Comment by avozicov** [comment]
No all terraform files are stored under `~/.terrahub/cache/jit/`
- I have created terrahub component
- Listed current `~/.terrahub/cache/jit/` folder to see that I have only 2 cached files from previous execution
- Executed terrahub init for new created component 
- A new cache file created in `~/.terrahub/cache/jit/` and terrahub commands worked as expected with this implementation 

![Screen Shot 2019-02-28 at 5.04.38 PM.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/cc7fbfbd-0a11-4761-9a7c-46d528f0d18a)

**Comment by eistrati** [comment]
Checked.
