### ISSUE TITLE
Error is missing if terrahub hook executed by bash fails

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#574]
As a result:
- TerraHub calls `thub/realtime/create` endpoint with `empty string value` associated for `error key`

Please refer to the following Jenkins job for more details:
https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-api/2022/console

**Comment by avozicov** [comment]
Fixed

<img width="795" alt="screen shot 2019-01-30 at 6 45 42 pm" src="https://user-images.githubusercontent.com/12330493/52075459-007c1f00-2595-11e9-82d7-31efa6b21348.png">

**Comment by eistrati** [comment]
Checked.
