### ISSUE TITLE
Add an option to customize the way components are displayed 

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#592]
Would be great to have an option to define the way the components list are displayed in CLI:
- tree view  
- comma separated values
- number 

This can be defined under global `.terrahub.json` 
for e.x. 
- tree view  : `true`
- comma separated values : `false`
- number  : `number`

**Comment by avozicov** [comment]
This is implemented, I was able to configure list option in root terrahub config and execute terrahub apply in terrahub-api project

```
{
  "format": "yml",
  "token": false,
  "usePhysicalCpu": false,
  "listLimit": 125 | -2 | less than component total 
}
```

will share the output in private for security reason

**Comment by eistrati** [comment]
Checked.
