### ISSUE TITLE
Make cache jit folders more user friendly

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#638]
# Feature Report
Make cache jit folders more user friendly

## Describe the Feature

Make cache jit folders more user friendly.

For example, instead of naming cache jit folders like below:

`[static_website] terraform plan -no-color -out=/var/lib/jenkins/.terrahub/cache/jit/62ce7375178298891f90bc8831804b4c/terraform.tfplan -input=false`

let's change the approach to something like

`[static_website] terraform plan -no-color -out=/var/lib/jenkins/.terrahub/cache/jit/static_website_62ce7375/terraform.tfplan -input=false`

**Comment by eistrati** [comment]
Looks like this is dependent on the following issue: https://github.com/TerraHubCorp/terrahub/issues/642

**Comment by avozicov** [comment]
Implemented 
- dir name contains `component_name` + `project_code`

![Screen Shot 2019-04-17 at 1.17.25 PM.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/8e199201-14a4-4aa0-b796-68610fe22bf9)

**Comment by eistrati** [comment]
Checked.
