### ISSUE TITLE
git-diff option does not include dependencies in execution list

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#658]
This issue has impact for automated deployment of `terrahub-api` and `lambda deployer` feature

**Comment by avozicov** [comment]
Fixed 

![Screen Shot 2019-04-12 at 5.38.54 PM.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/314ba1bd-cfaa-49bb-81c7-209dd0111bc0)

**Comment by eistrati** [comment]
Checked.
