### ISSUE TITLE
Implement update functionality for aws regions.json

### ISSUE THREAD

**Issue by const-andreyLu** [TerraHubCorp/terrahub#777]
# Feature Report
Implement update functionality for aws regions.json

## Describe the Feature

Similar to [Helper.updateMetadata](https://github.com/TerraHubCorp/terrahub/blob/master/bin/publish.js#L88), add in `publish.js` a function Helper.updateRegions() that will retrieve a list of supported regions directly from AWS (using ec2 describe-regions command)

**Comment by eistrati** [comment]
Checked.
