### ISSUE TITLE
Unable to configure through terminal an empty configuration file 

### ISSUE THREAD

**Issue by mnegura** [TerraHubCorp/terrahub#890]
# Bug Report

## Describe the Bug
Unable to configure through terminal an empty configuration file 

## To Reproduce

1. Create in a folder an empty `.terrahub.yml` file
2. 
```
terrahub configure --config component={}
❌ Cannot read property 'hasOwnProperty' of undefined
```

## Expected Behavior

Adding specified configuration to the `.yml` file

## Desktop

 - OS: macOS
 - Version v0.3.15

**Comment by eistrati** [comment]
Checked.
